"""邀請碼：invites 表 + users.invite_code

記下「這個帳號是被哪組邀請碼帶進來的」，以及站上發過哪些碼、各用掉幾次。
`users.invite_code` 帶了 server_default，既有帳號補欄位時才不會卡住。

Revision ID: 1a95b7066213
Revises: e741e301fae2
Create Date: 2026-09-29 17:44:26.894069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a95b7066213'
down_revision: Union[str, Sequence[str], None] = 'e741e301fae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_invites_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('invite_code', sa.String(length=32), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('invite_code')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_created_at'))
        batch_op.drop_index(batch_op.f('ix_invites_code'))

    op.drop_table('invites')
    # ### end Alembic commands ###
